url: https://javierjeronimo.es
name: Blog de Javier Jerónimo
description: >
  Blog de tecnología e ingeniería del
  software
email: your-email@example.com
twitter_username: javier_jeronimo
github_username:  javierjeronimo

markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
