url: https://javierjeronimo.es
title: Blog de Javier Jerónimo
description: >
  Blog de tecnología e ingeniería del
  software
email: git@javierjeronimo.es
twitter_username: javier_jeronimo
github_username:  javierjeronimo

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-architect