title: Blog de Javier Jerónimo
description: >
 Blog de Ingeniería del
 Software, Arquitectura y Ciber Seguridad
author: Javier Jerónimo
github: https://github.com/javierjeronimo
# about: I am freelance developer. Currently doing more in backend, focused in Python and Django.
# disqus_shortname: stackproblems
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/javierjeronimo"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/javierjeronimo"

urls:
    - text: Bienvenido
      url: /bienvenido
    - text: Curriculum Vitae
      url: /curriculum-vitae
    - text: XML Feed
      url: /feed.xml

url: "https://javierjeronimo.es"
baseurl: ""
permalink: /:year/:month/:day/:title/
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
